# Generated by Django 5.2.5 on 2025-11-03 04:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(db_index=True, unique=True)),
                (
                    "new_users",
                    models.IntegerField(
                        default=0, help_text="Yangi ro'yxatdan o'tganlar"
                    ),
                ),
                (
                    "verified_users",
                    models.IntegerField(
                        default=0, help_text="Tasdiqlangan foydalanuvchilar"
                    ),
                ),
                (
                    "total_users",
                    models.IntegerField(default=0, help_text="Jami foydalanuvchilar"),
                ),
                (
                    "total_logins",
                    models.IntegerField(default=0, help_text="Jami kirganlar"),
                ),
                (
                    "unique_logins",
                    models.IntegerField(default=0, help_text="Noyob foydalanuvchilar"),
                ),
                (
                    "new_tests",
                    models.IntegerField(default=0, help_text="Yangi testlar"),
                ),
                (
                    "completed_tests",
                    models.IntegerField(default=0, help_text="Tugallangan testlar"),
                ),
                (
                    "total_attempts",
                    models.IntegerField(default=0, help_text="Jami urinishlar"),
                ),
                (
                    "student_count",
                    models.IntegerField(default=0, help_text="O'quvchilar soni"),
                ),
                (
                    "teacher_count",
                    models.IntegerField(default=0, help_text="O'qituvchilar soni"),
                ),
                (
                    "admin_count",
                    models.IntegerField(default=0, help_text="Adminlar soni"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Kunlik Statistika",
                "verbose_name_plural": "Kunlik Statistikalar",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=255)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "response_time",
                    models.FloatField(blank=True, help_text="Milliseconds", null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sahifa Ko'rish",
                "verbose_name_plural": "Sahifa Ko'rishlar",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="analytics_p_timesta_b589d5_idx"
                    ),
                    models.Index(
                        fields=["path", "-timestamp"],
                        name="analytics_p_path_89b690_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("signup", "Signup"),
                            ("test_start", "Test Started"),
                            ("test_finish", "Test Finished"),
                        ],
                        max_length=20,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "session_duration",
                    models.DurationField(
                        blank=True,
                        help_text="Session davomiyligi (faqat logout uchun)",
                        null=True,
                    ),
                ),
                (
                    "test_id",
                    models.IntegerField(
                        blank=True,
                        help_text="Test ID (agar test bilan bog'liq bo'lsa)",
                        null=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Foydalanuvchi Faolligi",
                "verbose_name_plural": "Foydalanuvchi Faolliklari",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["-timestamp"], name="analytics_u_timesta_d8c879_idx"
                    ),
                    models.Index(
                        fields=["activity_type", "-timestamp"],
                        name="analytics_u_activit_7a754e_idx",
                    ),
                ],
            },
        ),
    ]
