# Generated by Django 4.2.16 on 2025-10-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0005_testretakerequest_is_used"),
    ]

    operations = [
        migrations.AlterField(
            model_name="test",
            name="shuffle_questions",
            field=models.BooleanField(
                default=True, help_text="Savollarni random tartibda ko'rsatish"
            ),
        ),
    ]
