# Generated by Django 4.2.16 on 2025-10-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0006_alter_test_shuffle_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Savol uchun rasm",
                null=True,
                upload_to="question_images/",
            ),
        ),
    ]
