# Generated by Django 4.2.16 on 2025-10-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0007_question_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="correct_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="incorrect_answers",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="unanswered",
            field=models.IntegerField(default=0),
        ),
    ]
