# Generated by Django 5.2.5 on 2025-11-04 03:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0008_testattempt_correct_answers_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="testattempt",
            name="current_question_index",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="is_terminated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="terminated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="terminated_attempts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="testattempt",
            name="termination_reason",
            field=models.TextField(blank=True),
        ),
    ]
