# Generated by Django 5.2.5 on 2025-11-28 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0009_testattempt_current_question_index_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testattempt",
            options={"ordering": ["-id"]},
        ),
    ]
