# Generated by Django 5.2.7 on 2025-12-04 17:00

from django.db import migrations


def remove_fields_if_exist(apps, schema_editor):
    """Safely remove fields only if they exist in the database"""
    # Check if columns exist before attempting to remove
    db_backend = schema_editor.connection.vendor
    
    try:
        with schema_editor.connection.cursor() as cursor:
            if db_backend == 'sqlite':
                # Get table info to check existing columns (SQLite)
                cursor.execute("PRAGMA table_info(tests_app_testattempt)")
                columns = [row[1] for row in cursor.fetchall()]
            else:
                # For PostgreSQL/MySQL, check information_schema
                cursor.execute("""
                    SELECT column_name 
                    FROM information_schema.columns 
                    WHERE table_name = 'tests_app_testattempt'
                """)
                columns = [row[0] for row in cursor.fetchall()]
            
            # Fields to remove
            fields_to_remove = ['correct_answers', 'incorrect_answers', 'unanswered']
            
            # Check which columns actually exist
            existing_fields = [f for f in fields_to_remove if f in columns]
            
            if not existing_fields:
                print("Fields do not exist in database, skipping database removal")
                return
            
            # If columns exist, we would need to remove them
            # But for SQLite, DROP COLUMN requires table recreation which is complex
            # Since these columns shouldn't exist, we'll just skip
            print(f"Note: Fields {existing_fields} would be removed if they existed")
            
    except Exception as e:
        # Ignore errors - columns likely don't exist
        print(f"Note: {e}")


def reverse_remove_fields(apps, schema_editor):
    """Reverse migration - add fields back if needed"""
    # This is a no-op as we're removing fields that shouldn't exist
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0010_alter_testattempt_options"),
    ]

    operations = [
        # Use SeparateDatabaseAndState to handle DB and model state separately
        migrations.SeparateDatabaseAndState(
            # Database operations - safely check and remove if exists
            database_operations=[
                migrations.RunPython(
                    remove_fields_if_exist,
                    reverse_remove_fields,
                    atomic=False,
                ),
            ],
            # State operations - update Django's model metadata only
            state_operations=[
                migrations.RemoveField(
                    model_name="testattempt",
                    name="correct_answers",
                ),
                migrations.RemoveField(
                    model_name="testattempt",
                    name="incorrect_answers",
                ),
                migrations.RemoveField(
                    model_name="testattempt",
                    name="unanswered",
                ),
            ],
        ),
    ]
