# Generated by Django 5.2.5 on 2026-02-13 07:07
# DB da correct_answers, incorrect_answers, unanswered allaqachon mavjud (0008)
# Faqat model state ni yangilaymiz

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0011_remove_testattempt_correct_answers_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # DB da ustunlar bor, qo'shish shart emas
            state_operations=[
                migrations.AddField(
                    model_name="testattempt",
                    name="correct_answers",
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="testattempt",
                    name="incorrect_answers",
                    field=models.IntegerField(default=0),
                ),
                migrations.AddField(
                    model_name="testattempt",
                    name="unanswered",
                    field=models.IntegerField(default=0),
                ),
            ],
        ),
    ]
