# Generated by Django 5.2.5 on 2026-02-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0012_add_back_testattempt_counters"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="question_type",
            field=models.CharField(
                choices=[
                    ("single_choice", "Single Choice"),
                    ("multiple_choice", "Multiple Choice"),
                    ("text_answer", "Text Answer"),
                ],
                default="single_choice",
                max_length=15,
            ),
        ),
    ]
