# Generated by Django 5.2.5 on 2026-03-10 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tests_app", "0014_remove_testattempt_counter_columns"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL uchun, masalan: fizika, ingliz-tili",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        default="fa-book",
                        help_text="Font Awesome icon, masalan: fa-atom",
                        max_length=50,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
    ]
